---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-74-was855-chef13
    driver:
      box: centos-74-was855-chef13
      box_url: https://s3.us-east-2.amazonaws.com/devops-perficient-images/boxes/centos-74-was855-chef13.box
      customize:
        memory: 4096

suites:
  - name: default
    run_list:
     - recipe[was_master::prerequisites]
     - recipe[was_master::create_profiles]
     - recipe[was_master::set_jvm_log_size]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      was:
        host: default-centos-74-was855-chef13.vagrantup.com
        profile_name: Dmgr01
        soap_port: 8879
        cell_name: Defaul01Cell
        node_name: Default02Node
        server_name: dmgr
        java_option_first: -Xms128m
        java_option_second: -Xmx256m
